
USE master;
GO
DROP DATABASE IMPORTER;
CREATE DATABASE IMPORTER
ON
(NAME = IMPORTER_DAT,
FILENAME = 'h:\Sql Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\importerdat.mdf',
SIZE = 10,
MAXSIZE = 50,
FILEGROWTH = 5)
LOG ON 
( NAME = IMPORTER_LOG,
  FILENAME = 'h:\Sql Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\importerlog.ldf',
  SIZE = 10,
  MAXSIZE = 50,
  FILEGROWTH = 5);
GO
USE IMPORTER;
GO
CREATE SCHEMA PRH;
GO
IF OBJECT_ID('IMPORTER.PRH.LNPRH','U') IS NOT NULL DROP TABLE IMPORTER.PRH.LNPRH;
CREATE TABLE IMPORTER.PRH.LNPRH(
 WTCH SMALLINT NOT NULL PRIMARY KEY,
 WPRH  DECIMAL(3,2) NOT NULL,
  NTYP CHAR(3)   NOT NULL DEFAULT 'PRH',
  ONFZ TINYINT NOT NULL,
  CGEN DATETIME2(7) NOT NULL DEFAULT '1900-01-01 00:00:00',
  DPIM DATETIME2(7) NOT NULL DEFAULT '1900-01-01 00:00:00',
  DKIM DATETIME2(7) DEFAULT '1900-01-01 00:00:00'
 )
;
IF OBJECT_ID('IMPORTER.PRH.LJDMR','U') IS NOT NULL DROP TABLE IMPORTER.PRH.LJDMR;
CREATE TABLE  IMPORTER.PRH.LJDMR
(
 KDJM TINYINT NOT NULL PRIMARY KEY,
 NZJM VARCHAR(4) COLLATE POLISH_CI_AS  NOT NULL,
 STJM CHAR(1) COLLATE POLISH_CI_AS  NOT NULL
);
IF OBJECT_ID('IMPORTER.PRH.LGRSU','U') IS NOT NULL DROP TABLE IMPORTER.PRH.LGRSU;
CREATE  TABLE IMPORTER.PRH.LGRSU
(
 KGRS SMALLINT NOT NULL PRIMARY KEY,
 NGRS VARCHAR(90) COLLATE POLISH_CI_AS NOT NULL,
 KDJM TINYINT NOT NULL,
 SGRS CHAR(1) COLLATE POLISH_CI_AS  NOT NULL
);

IF OBJECT_ID('IMPORTER.PRH.LHGRS','U') IS NOT NULL DROP TABLE IMPORTER.PRH.LHGRS;
CREATE  TABLE IMPORTER.PRH.LHGRS
(
 IHGS INT IDENTITY(1,1) NOT NULL PRIMARY KEY ,
 KGRS SMALLINT NOT NULL ,
 NGRS VARCHAR(90) COLLATE POLISH_CI_AS NOT NULL,
 KDJM TINYINT NOT NULL,
 SGRS CHAR(1) COLLATE POLISH_CI_AS  NOT NULL,
 WTCH SMALLINT NOT NULL
);

IF OBJECT_ID('IMPORTER.PRH.LPRHA','U') IS NOT NULL DROP TABLE IMPORTER.PRH.LPRHA;

CREATE TABLE IMPORTER.PRH.LPRHA
(
 IDPR INT IDENTITY(1,1) NOT NULL  PRIMARY KEY ,
 WTCH SMALLINT NOT NULL,
 KPRH CHAR(6) COLLATE POLISH_CI_AS NOT NULL,
 KEAN CHAR(14) COLLATE POLISH_CI_AS ,
 SPRH CHAR(9) COLLATE POLISH_CI_AS ,
 KGRS SMALLINT NOT NULL ,
 NPRH VARCHAR(90)  COLLATE POLISH_CI_AS NOT NULL,
 PPRH VARCHAR(90) COLLATE POLISH_CI_AS NOT NULL,
 DPRH VARCHAR(90) COLLATE POLISH_CI_AS NOT NULL,
 OPRH VARCHAR(90) COLLATE POLISH_CI_AS NOT NULL,
 POPR VARCHAR(90) COLLATE POLISH_CI_AS NOT NULL,
 IPRH DECIMAL(20,5) NOT NULL,
 LPRH DECIMAL(20,5) NOT NULL,
 STPR CHAR(1) COLLATE POLISH_CI_AS  NOT NULL
);

IF OBJECT_ID('IMPORTER.PRH.TRPRH','U') IS NOT NULL DROP TABLE IMPORTER.PRH.TRPRH;

CREATE TABLE IMPORTER.PRH.TRPRH
(
  IDTR INT IDENTITY(1,1) NOT NULL  PRIMARY KEY ,
  IDPR INT NOT NULL  ,
  KKAT CHAR(2) COLLATE POLISH_CI_AS NOT NULL,
  DTPO DATE NOT NULL,
  DTKO DATE ,
  TBAZ DECIMAL(10,4) NOT NULL,
  LJRO DECIMAL(10,4) NOT NULL
)

ALTER TABLE IMPORTER.PRH.LGRSU ADD CONSTRAINT FK_LGRSU_LJDMR FOREIGN KEY(KDJM) REFERENCES IMPORTER.PRH.LJDMR(KDJM) ON DELETE NO ACTION
ON UPDATE NO ACTION ;

ALTER TABLE IMPORTER.PRH.LHGRS ADD CONSTRAINT FK_LHGRS_LJDMR FOREIGN KEY(KDJM) REFERENCES IMPORTER.PRH.LJDMR(KDJM) ON DELETE NO ACTION
ON UPDATE NO ACTION ;
ALTER TABLE IMPORTER.PRH.LHGRS ADD CONSTRAINT FK_LHGRS_LNPRH FOREIGN KEY(WTCH) REFERENCES IMPORTER.PRH.LNPRH(WTCH) ON DELETE NO ACTION
ON UPDATE NO ACTION ;
ALTER TABLE IMPORTER.PRH.LHGRS ADD CONSTRAINT FK_LHGRS_LGRSU FOREIGN KEY(KGRS) REFERENCES IMPORTER.PRH.LGRSU(KGRS) ON DELETE NO ACTION
ON UPDATE NO ACTION ;



IF OBJECT_ID('IMPORTER.PRH.LNPRH_ADD','P') IS NOT NULL DROP PROCEDURE PRH.LNPRH_ADD;

USE IMPORTER;
GO
CREATE PROCEDURE PRH.LNPRH_ADD
	@AWTCH INT,
	@AWPRH DECIMAL(3,2),
	@AONFZ TINYINT,
	@ACGEN DATETIME2
AS
 SET NOCOUNT ON;
INSERT INTO IMPORTER.PRH.LNPRH(WTCH,WPRH,ONFZ,CGEN,DPIM) VALUES (@AWTCH,@AWPRH,@AONFZ,@ACGEN,CURRENT_TIMESTAMP);
GO

--EXECUTE IMPORTER.PRH.LNPRH_ADD @AWTCH=1,@AWPRH=5.0,@AONFZ=17,@ACGEN='2014-01-12 13:32:35';

IF OBJECT_ID('IMPORTER.PRH.LNPRH_EDT','P') IS NOT NULL DROP PROCEDURE PRH.LNPRH_EDT;

GO

CREATE PROCEDURE PRH.LNPRH_EDT
	@AWTCH INT
AS
	SET NOCOUNT ON;
	UPDATE PRH.LNPRH SET DKIM=CURRENT_TIMESTAMP WHERE WTCH=@AWTCH;
GO
GO
USE IMPORTER;
--EXECUTE IMPORTER.PRH.LNPRH_EDT @AWTCH=1;

--SELECT * FROM IMPORTER.PRH.LNPRH;

IF OBJECT_ID('IMPORTER.PRH.LJDMR_ADD','P') IS NOT NULL DROP PROCEDURE PRH.LJDMR_ADD;

GO
CREATE PROCEDURE PRH.LJDMR_ADD
	@AKDJM TINYINT,
	@ANZJM VARCHAR(4),
	@ASTJM CHAR(1)
AS
 SET NOCOUNT ON;


 IF NOT EXISTS( SELECT KDJM  FROM LJDMR WHERE KDJM=@AKDJM AND NZJM=@ANZJM AND STJM=@ASTJM )
 BEGIN
	INSERT INTO IMPORTER.PRH.LJDMR(KDJM,NZJM,STJM) VALUES(@AKDJM,@ANZJM,@ASTJM)
 END
 ELSE
 BEGIN
	UPDATE IMPORTER.PRH.LJDMR SET NZJM=@ANZJM,STJM=@ASTJM WHERE KDJM=@AKDJM
 END
GO
USE IMPORTER;
--EXECUTE IMPORTER.PRH.LJDMR_ADD @AKDJM=1,@ANZJM='JM',@ASTJM='A';
--SELECT * FROM PRH.LJDMR;

USE IMPORTER;
IF OBJECT_ID('IMPORTER.PRH.LGRSU_ADD','P') IS NOT NULL DROP PROCEDURE PRH.LGRSU_ADD;
GO
CREATE PROCEDURE PRH.LGRSU_ADD
	@AWTCH INT,
	@AKGRS INT,
	@ANGRS VARCHAR(90),
	@AKDJM INT,
	@ASGRS CHAR(1)
AS
DECLARE @ErrorMessage    NVARCHAR(4000),
        @ErrorNumber     INT,
        @ErrorSeverity   INT,
        @ErrorState      INT,
        @ErrorLine       INT,
        @ErrorProcedure  NVARCHAR(200);
SET NOCOUNT ON
IF NOT EXISTS(SELECT KGRS  FROM PRH.LGRSU WHERE KGRS=@AKGRS AND NGRS=@ANGRS AND KDJM=@AKDJM AND SGRS=@ASGRS)
 BEGIN
  BEGIN TRY
	INSERT INTO PRH.LGRSU(KGRS,NGRS,KDJM,SGRS) VALUES(@AKGRS,@ANGRS,@AKDJM,@ASGRS);
  END TRY
  BEGIN CATCH
	SELECT @ErrorMessage =  ERROR_MESSAGE();
		--	PRINT N'BLAD:'+@ErrorMessage;
		RAISERROR 
        (
        @ErrorMessage, 
        @ErrorSeverity, 
        1,               
        @ErrorNumber,    -- parameter: original error number.
        @ErrorSeverity,  -- parameter: original error severity.
        @ErrorState,     -- parameter: original error state.
        @ErrorProcedure, -- parameter: original error procedure name.
        @ErrorLine       -- parameter: original error line number.
        );
  END CATCH
	INSERT INTO PRH.LHGRS(KGRS,NGRS,KDJM,SGRS,WTCH) VALUES(@AKGRS,@ANGRS,@AKDJM,@ASGRS,@AWTCH)
 END
ELSE
 BEGIN
	UPDATE PRH.LGRSU SET NGRS=@ANGRS,KDJM=@AKDJM,SGRS=@ASGRS WHERE KGRS=@AKGRS;
	INSERT INTO PRH.LHGRS(KGRS,NGRS,KDJM,SGRS,WTCH) VALUES(@AKGRS,@ANGRS,@AKDJM,@ASGRS,@AWTCH); 
END
GO
/*EXECUTE IMPORTER.PRH.LGRSU_ADD @AWTCH=1,@AKGRS=3,@ANGRS='TEST',@AKDJM=1,@ASGRS='T';
SELECT * FROM PRH.LGRSU;
SELECT * FROM IMPORTER.PRH.LHGRS;
*/
USE IMPORTER;
IF OBJECT_ID('IMPORTER.PRH.LPRHA_ADD','P') IS NOT NULL DROP PROCEDURE PRH.LPRHA_ADD;
GO
CREATE PROCEDURE PRH.LPRHA_ADD
 @AWTCH INT , @AKEAN CHAR(14) ,@ASPRH CHAR(9) ,@AKGRS SMALLINT  ,
 @ANPRH VARCHAR(90) ,@APPRH VARCHAR(90),@ADPRH VARCHAR(90) ,@AOPRH VARCHAR(90),
 @APOPR VARCHAR(90) ,@AIPRH DECIMAL(20,5),@ALPRH DECIMAL(20,5),@ASTPR CHAR(1) ,@AKPRH CHAR(6) 
 AS
 DECLARE @ErrorMessage NVARCHAR(4000),
		 @ErrorNumber     INT,
         @ErrorSeverity   INT
 SET NOCOUNT ON;
 BEGIN TRY
	INSERT INTO IMPORTER.PRH.LPRHA(WTCH ,KEAN,SPRH,KGRS,NPRH,PPRH,DPRH,OPRH,POPR,IPRH,LPRH,STPR,KPRH) 
	VALUES(@AWTCH ,@AKEAN,@ASPRH,@AKGRS,@ANPRH,@APPRH,@ADPRH,@AOPRH,@APOPR,@AIPRH,@ALPRH,@ASTPR,@AKPRH);
 END TRY
 BEGIN CATCH
	SELECT @ErrorMessage =  ERROR_MESSAGE();
	SELECT @ErrorNumber = ERROR_NUMBER();
	SELECT @ErrorSeverity= ERROR_SEVERITY();
	RAISERROR(@ErrorMessage,@ErrorSeverity,1,@ErrorNumber);
 END CATCH
GO

/*EXECUTE IMPORTER.PRH.LPRHA_ADD @AWTCH=1,@AKEAN='4353453535',@ASPRH='342',@AKGRS=1,@ANPRH='TEST',@APPRH='TEST',
@ADPRH='TEST',@AOPRH='PJ',@APOPR='JS',@AIPRH=20.1,@ALPRH=23.5,@ASTPR='T',@AKPRH='232232';

SELECT * FROM IMPORTER.PRH.LPRHA;
*/

USE IMPORTER;
IF OBJECT_ID('IMPORTER.PRH.TRPRH_ADD','P') IS NOT NULL DROP PROCEDURE PRH.TRPRH_ADD;
GO
GO
CREATE PROCEDURE PRH.TRPRH_ADD
 @AIDPR INT  ,@AKKAT CHAR(2) ,@ADTPO DATE ,@ADTKO DATE ,@ATBAZ DECIMAL(10,4),
 @ALJRO DECIMAL(10,4)
 AS
 DECLARE @ErrorMessage NVARCHAR(4000),
		 @ErrorNumber     INT,
         @ErrorSeverity   INT
 SET NOCOUNT ON;
 BEGIN TRY
	INSERT INTO PRH.TRPRH(IDPR,KKAT,DTPO, DTKO,TBAZ,LJRO) VALUES(@AIDPR,@AKKAT,@ADTPO, @ADTKO,@ATBAZ,@ALJRO);
 END TRY
 BEGIN CATCH
	SELECT @ErrorMessage =  ERROR_MESSAGE();
	SELECT @ErrorNumber = ERROR_NUMBER();
	SELECT @ErrorSeverity= ERROR_SEVERITY();
	RAISERROR(@ErrorMessage,@ErrorSeverity,1,@ErrorNumber);
 END CATCH
GO
EXECUTE PRH.TRPRH_ADD @AIDPR=1,@AKKAT='WE',@ADTPO='2014-01-01',@ADTKO='2014-01-31',@ATBAZ=34.1240,@ALJRO=10.0000;
SELECT * FROM PRH.TRPRH;